spring:
  application:
    name: review-system
  
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/review_system_db}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_USER_PWD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: ${DATABASE_POOL_SIZE:5}
  
  jpa:
    hibernate:
      ddl-auto: ${DATABASE_DDL_MODE:update}
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false

server:
  port: ${REVIEW_SYSTEM_SERVICE_PORT:8085}

logging:
  level:
    com.reviewsystem: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:#{null}}
  expiration: ${JWT_EXPIRATION:900000}
